# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://magistak.github.io',
                'git_url': 'https://github.com/magistak/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.hello': { 'nbdev_hello_world.hello.hello': ('hello.html#hello', 'nbdev_hello_world/hello.py'),
                                         'nbdev_hello_world.hello.say_hello': ('hello.html#say_hello', 'nbdev_hello_world/hello.py')}}}
